name: Check images

on:
  schedule:
  - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  tester1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download dep-scan
      run: |
        oras pull ghcr.io/ngcloudsec/vdb:v1 -o $VDB_HOME
        oras pull ghcr.io/ngcloudsec/depscan:v3 -o $VDB_HOME
        chmod +x ./depscan/depscan-linux-amd64
      env:
        VDB_HOME: depscan
    - name: Perform scan
      run: |
        mkdir -p results
        for i in `cat repo-list.txt`; do
          echo "Scanning image $i"
          ./depscan/depscan-linux-amd64 -t docker -i $i -o results/depscan-$i.json --no-error
          echo "----------------------"
        done
        ls -ltr results
      env:
        VDB_HOME: depscan
    - uses: actions/upload-artifact@v1
      with:
        path: ./results
        name: depscan-results1

  tester2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download dep-scan
      run: |
        oras pull ghcr.io/ngcloudsec/vdb:v1 -o $VDB_HOME
        oras pull ghcr.io/ngcloudsec/depscan:v3 -o $VDB_HOME
        chmod +x ./depscan/depscan-linux-amd64
      env:
        VDB_HOME: depscan
    - name: Perform scan
      run: |
        mkdir -p results
        for i in `cat repo-list.txt`; do
          echo "Scanning image $i"
          ./depscan/depscan-linux-amd64 -t docker -i $i -o results/depscan-$i.json --no-error
          echo "----------------------"
        done
        ls -ltr results
      env:
        VDB_HOME: depscan
    - uses: actions/upload-artifact@v1
      with:
        path: ./results
        name: depscan-results2

  tester3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download dep-scan
      run: |
        oras pull ghcr.io/ngcloudsec/vdb:v1 -o $VDB_HOME
        oras pull ghcr.io/ngcloudsec/depscan:v3 -o $VDB_HOME
        chmod +x ./depscan/depscan-linux-amd64
      env:
        VDB_HOME: depscan
    - name: Perform scan
      run: |
        mkdir -p results
        for i in `cat repo-list.txt`; do
          echo "Scanning image $i"
          ./depscan/depscan-linux-amd64 -t docker -i $i -o results/depscan-$i.json --no-error
          echo "----------------------"
        done
        ls -ltr results
      env:
        VDB_HOME: depscan
    - uses: actions/upload-artifact@v1
      with:
        path: ./results
        name: depscan-results3

  tester4:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download dep-scan
      run: |
        oras pull ghcr.io/ngcloudsec/vdb:v1 -o $VDB_HOME
        oras pull ghcr.io/ngcloudsec/depscan:v3 -o $VDB_HOME
        chmod +x ./depscan/depscan-linux-amd64
      env:
        VDB_HOME: depscan
    - name: Perform scan
      run: |
        mkdir -p results
        for i in `cat repo-list.txt`; do
          echo "Scanning image $i"
          ./depscan/depscan-linux-amd64 -t docker -i $i -o results/depscan-$i.json --no-error
          echo "----------------------"
        done
        ls -ltr results
      env:
        VDB_HOME: depscan
    - uses: actions/upload-artifact@v1
      with:
        path: ./results
        name: depscan-results4
        
